### ISSUE TITLE
Support for ActiveSupport 4.2?

### ISSUE THREAD

**Issue by eashman** [seamusabshere/remote_table#21]
When I tried to use this Gem with ActiveSupport 4.2, it won't even load.  Any ideas?

Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `each'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/eashman/.rvm/gems/ruby-2.1.2/gems/remote_table-3.3.0/lib/remote_table.rb:8:in `<top (required)>'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/eashman/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from xltest.rb:1:in `<main>'

**Comment by switzersc** [comment]
I'm having the same problem.

**Comment by HerbCSO** [comment]
Same here - any chance you could look into this?

**Comment by dwillis** [comment]
There's a work-around for it, but it does require installing ActiveSupport and then doing:

require 'active_support'
require 'active_support/deprecation'

before you require remote_table.

**Comment by seamusabshere** [comment]
i believe this is fixed in https://github.com/seamusabshere/remote_table/commit/8cf294634c0cbf5db66e4d7b37a3998290eb3b9b
